image:
  repository: registry.cn-shanghai.aliyuncs.com/hsin/edusoho
  pullPolicy: IfNotPresent
  tag: "8.7.15"
  
replicaCount: 1
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 80

livenessProbe: {}
readinessProbe: {}

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

persistent:
  - name: private-files
    enabled: true
    mountPoint: /var/www/edusoho/app/data/private_files
    annotations: {}
    accessModes: ReadWriteMany
    storage: 1G
  - name: udisk
    enabled: false
    mountPoint: /var/www/edusoho/app/data/udisk
    annotations: {}
    accessModes: ReadWriteOnce
    storage: 1G