image:
  repository: registry.cn-shanghai.aliyuncs.com/hsin/edusoho
  pullPolicy: IfNotPresent
  tag: "7.1"
  
replicaCount: 1
imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: NodePort
  port: 80

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 256Mi

nodeSelector: {}

tolerations: []

affinity: {}

serverBlock: |
  server {
      listen 80 default_server;

      # 网站的域名
      server_name _;

      # 301 跳转可以在 nginx 中配置

      # 程序的安装路径
      root /var/www/edusoho/web;

      # 日志路径
      #access_log /var/log/nginx/example.com.access.log;
      #error_log /var/log/nginx/example.com.error.log;

      location / {
        index app.php;
        try_files $uri @rewriteapp;
      }

      location @rewriteapp {
        rewrite ^(.*)$ /app.php/$1 last;
      }

      location ~ ^/udisk {
        internal;
        root /var/www/edusoho/app/data/;
      }
      location ~ ^/(app|app_dev)\.php(/|$) {
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param  HTTPS              off;
        fastcgi_param HTTP_X-Sendfile-Type X-Accel-Redirect;
        fastcgi_param HTTP_X-Accel-Mapping /udisk=/var/www/edusoho/app/data/udisk;
        fastcgi_buffer_size 128k;
        fastcgi_buffers 8 128k;
      }

      # 配置设置图片格式文件
      location ~* \.(jpg|jpeg|gif|png|ico|swf)$ {
        # 过期时间为 3 年
        expires 3y;
        
        # 关闭日志记录
        access_log off;

        # 关闭 gzip 压缩，减少 CPU 消耗，因为图片的压缩率不高。
        gzip off;
      }

      # 配置 css/js 文件
      location ~* \.(css|js)$ {
        access_log off;
        expires 3y;
      }

      # 禁止用户上传目录下所有 .php 文件的访问，提高安全性
      location ~ ^/files/.*\.(php|php7.0)$ {
        deny all;
      }

      location ~ \.php$ {
        # [改] 请根据实际 php-fpm 运行的方式修改
        fastcgi_pass   127.0.0.1:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param  HTTPS              off;
        fastcgi_param  HTTP_PROXY         "";
      }
    }

webVolumeName: web-volume

persistentVolumeClaim:
  enabled: false
  name: www-pvc
  accessModes: ReadWriteMany
  storage: 1Gi