apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: www-pvc
  namespace: edusoho
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: edusoho
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
