apiVersion: apps/v1
kind: Deployment
metadata:
  name: edusoho-web
  namespace: edusoho
spec:
  selector:
    matchLabels:
      app: edusoho-web
  template:
    metadata:
      labels:
        app: edusoho-web
    spec:
      containers:
        - name: edusoho-web
          image: registry.cn-shanghai.aliyuncs.com/hsin/edusoho:8.7.15
          resources:
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 80
              name: nginx-port
          volumeMounts:
            - mountPath: /var/www/edusoho/app/data/private_files
              name: private-files
            - mountPath: /var/www/edusoho/app/data/udisk
              name: udisk
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "nginx -s stop"]
          readinessProbe:
            initialDelaySeconds: 10
            httpGet:
              path: "/"
              port: nginx-port
          # livenessProbe:
          #   initialDelaySeconds: 30
          #   timeoutSeconds: 3
          #   periodSeconds: 30
          #   httpGet:
          #     path: "/"
          #     port: nginx-port
      volumes:
        - name: private-files
          persistentVolumeClaim:
            claimName: private-files
        - name: udisk
          persistentVolumeClaim:
            claimName: udisk
