# apiVersion: v1
# kind: ConfigMap
# metadata:
#   labels:
#     app: ingress-nginx
#   name: nginx-configuration
#   namespace: ingress-nginx
# data:
#   hsts: "true"
#   hsts-include-subdomains: "true"
#   hsts-max-age: "0"
#   hsts-preload: "false"

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: edusoho-ingress
  namespace: edusoho
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($scheme = https) {
        more_clear_headers "Strict-Transport-Security";
      }
spec:
  rules:
    - host: edusoho.org
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-svc
              servicePort: 80
