version: "3.4"

services:
  db:
    image: mysql/mysql-server:8.0.23-1.1.19
    container_name: edusoho-db
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - db:/var/lib/mysql
    networks:
      - edusoho
    restart: always
  web:
    image: registry.cn-shanghai.aliyuncs.com/hsin/edusoho:21.1.6
    container_name: edusoho-web
    depends_on:
      - db
    environment:
      TZ: Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/"]
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - edusoho
    ports:
      - 80:80
      # nginx vts status
      #- 8080:8080
    restart: always

volumes:
  db:

networks:
  edusoho:

