version: "3"

services:
  db:
    image: mysql:5.7
    container_name: edusoho-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - db:/var/lib/mysql
    networks:
      - edusoho
    restart: always
  web:
    image: registry.cn-shanghai.aliyuncs.com/hsin/edusoho:8.7.15
    container_name: edusoho-web
    environment:
      TZ: Asia/Shanghai
    volumes:
      - private_files:/var/www/edusoho/app/data/private_files
      - udisk:/var/www/edusoho/app/data/udisk
    networks:
      - edusoho
    ports:
      - 80:80
    restart: always

volumes:
  private_files:
  udisk:
  db:

networks:
  edusoho:
