{{- $fullname := include "edusoho.fullname" . }}
{{- range .Values.persistent }}
{{- if .enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  {{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    app: {{ $fullname }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
spec:
  accessModes:
    - {{ .accessModes | quote }}
  resources:
    requests:
      storage: {{ .storage | quote }}
---
{{- end }}
{{- end }}