apiVersion: v1
kind: Service
metadata:
  name: {{ include "edusoho.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "edusoho.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "edusoho.fullname" . }}
    release: "{{ .Release.Name }}"
