apiVersion: apps/v1
kind: Deployment
metadata:
  name: edusoho-web
  namespace: edusoho
spec:
  selector:
    matchLabels:
      app: edusoho-web
  template:
    metadata:
      labels:
        app: edusoho-web
    spec:
      containers:
        - name: edusoho-web
          image: registry.cn-shanghai.aliyuncs.com/hsin/edusoho:21.1.6
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: nginx-port
