apiVersion: apps/v1
kind: Deployment
metadata:
  name: edusoho-web
  namespace: edusoho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edusoho-web
  template:
    metadata:
      labels:
        app: edusoho-web
    spec:
      initContainers:
        - name: download-edusoho
          command:
            [
              "sh",
              "-c",
              "if [ ! -d /data/edusoho -a ! -f /data/edusoho.zip ]; then cd /data && wget http://download.edusoho.com/edusoho-8.7.15.zip -O edusoho.zip && unzip edusoho.zip && chown www-data:www-data -R /data/edusoho; fi",
            ]
          image: busybox
          volumeMounts:
            - mountPath: /data
              name: edusoho-www
      containers:
        - name: edusoho-nginx
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: nginx-port
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              name: nginx-cm
            - mountPath: /etc/nginx/conf.d/default.conf
              subPath: edusoho.conf
              name: nginx-vhost-cm
            - mountPath: /var/www
              name: edusoho-www
        - name: edusoho-php
          image: registry.cn-hangzhou.aliyuncs.com/edusoho-1/php-fpm:7.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
              name: php-port
          volumeMounts:
            - mountPath: /var/www
              name: edusoho-www
      volumes:
        - name: nginx-cm
          configMap:
            name: nginx-cm
        - name: nginx-vhost-cm
          configMap:
            name: nginx-vhost-cm
        - name: edusoho-www
          emptyDir: {}
