- name: Ensure group exist
  group:
    name: "{{ user.group | default(user.name) }}"

- name: Ensure user exist
  user:
    name: "{{ user.name }}"
    group: "{{ user.group | default(user.name) }}"

- name: Install php
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Restart PHP
  meta: flush_handlers
