- name: Ubuntu| Install software-properties-common
  apt:
    name: software-properties-common
    state: present
    update_cache: yes

- name: Ubuntu | Add PHP repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Ubuntu | Install php 7.1
  apt:
    name:
      - php-pear
      - php7.1-cli
      - php7.1-common
      - php7.1-curl
      - php7.1-dev
      - php7.1-fpm
      - php7.1-json
      - php7.1-mbstring
      - php7.1-mcrypt
      - php7.1-mysql
      - php7.1-opcache
      - php7.1-zip
      - php7.1-intl
      - php7.1-gd
      - php7.1-xml

- name: Ubuntu | Add config to php.ini
  blockinfile:
    path: /etc/php/7.1/fpm/php.ini
    block: "{{ php_vars }}"
    backup: yes
  notify: Ubuntu restart php

- name: Ubuntu | Change PHP user
  replace:
    path: /etc/php/7.1/fpm/pool.d/www.conf
    regexp: "www-data"
    replace: "{{ user.name }}"
  notify: Ubuntu restart php

- name: Ubunt | Change PHP-FPM listen
  lineinfile:
    dest: /etc/php/7.1/fpm/pool.d/www.conf
    line: "listen = 127.0.0.1:9000"
    backup: yes
  notify: Ubuntu restart php
