---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Ubuntu1604
    groups:
      - web
      - db
    image: "geerlingguy/docker-ubuntu1604-ansible"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: true
  - name: Ubuntu1804
    groups:
      - web
      - db
    image: "geerlingguy/docker-ubuntu1804-ansible"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: true
  - name: Ubuntu2004
    groups:
      - web
      - db
    image: "geerlingguy/docker-ubuntu2004-ansible"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: true
  - name: CentOS7
    groups:
      - web
      - db
    image: "geerlingguy/docker-centos7-ansible"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: true
  - name: CentOS8
    groups:
      - web
      - db
    image: "geerlingguy/docker-centos8-ansible"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    prepare: ../../molecule/prepare.yml
  #options:
    #vvv: True
  #config_options:
    #defaults:
      #callback_whitelist: profile_tasks
  inventory:
    links:
      group_vars: ../../group_vars
  env:
    ANSIBLE_ROLES_PATH: ../../roles
scenario:
  name: default
verifier:
  name: ansible
