- name: Ensure nginx group exist
  group:
    name: "{{ user.group }}"

- name: Ensure nginx user exist
  user:
    name: "{{ user.name }}"
    group: "{{ user.group | default(user.name) }}"

- name: Install nginx source
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Install nginx
  package:
    name: nginx
    state: present
    update_cache: yes

- name: Modify nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: restart nginx

- name: Add edusoho.conf
  template:
    src: edusoho.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    backup: yes
  notify: restart nginx

- name: Restart nginx
  meta: flush_handlers
