- name: Ubuntu | Install dependencies
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
    state: present
    update_cache: yes

- name: Ubuntu | Add nginx gpg key
  apt_key:
    url: "http://mirrors.ustc.edu.cn/nginx/keys/nginx_signing.key"
    state: present

- name: Ubuntu | Add nginx repository
  apt_repository:
    repo: "deb http://mirrors.ustc.edu.cn/nginx/ubuntu/ {{ ansible_distribution_release }} nginx"
    filename: nginx
    state: present
