dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${namespace:-robertdebock}/${image:-fedora}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
