#---
#dependency:
#  name: galaxy
#driver:
#  name: docker
#platforms:
#  - name: "{{ role_name }}-${image:-fedora}-${tag:-latest}${TOX_ENVNAME}"
#    image: "${namespace:-robertdebock}/${image:-fedora}:${tag:-latest}"
#    command: /sbin/init
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    privileged: yes
#    pre_build_image: yes
#provisioner:
#  name: ansible
#verifier:
#  name: ansible
#scenario:
#  name: default

---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${namespace:-robertdebock}/${image:-fedora}:${tag:-latest}"
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: yes
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
