---
name: Baremetal script ci

on:
  - push
      #  paths:
      #    - "baremetal/**"
      #pull_request:
      #  paths:
      #    - "baremetal/**"

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        images:
          - geerlingguy/docker-centos7-ansible
          - geerlingguy/docker-centos8-ansible
          - geerlingguy/docker-ubuntu1604-ansible
          - geerlingguy/docker-ubuntu1804-ansible
          - geerlingguy/docker-ubuntu2004-ansible
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Disable mysql apparmor
        run: |
          sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
          sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: Start docker container
        run: |
          docker run -d -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} -w ${GITHUB_WORKSPACE} -v /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged --name test ${{ matrix.images }} /sbin/init
      - name: Exec script
        run: |
          docker exec test bash -c 'cd baremetal && bash deploy.sh'
      - name: Test Nginx and PHP
        run: |
          docker exec test bash -c 'curl -L 127.0.0.1'
      - name: Test MySQL
        run: |
          docker exec test bash -c 'systemctl status mysql || systemctl status mysqld || true'
