---
name: Baremetal script ci

on:
  - push
      #  paths:
      #    - "baremetal/**"
      #pull_request:
      #  paths:
      #    - "baremetal/**"

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
    container:
        image:  centos:7
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
        options: "--privileged --init"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        #- name: Disable mysql apparmor
        #  run: |
        #    sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
        #    sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: Test script in baremetal
        run: |
          cd baremetal
          sudo bash deploy.sh
      - name: curl localhost
        run: curl -L localhost
      - name: mysql status
        run: sudo systemctl status mysql
