---
name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          sudo apt install docker
          sudo systemctl status docker
          sudo systemctl restart docker
          python3 -m pip install --upgrade pip
          python3 -m pip install ansible molecule docker
      - name: Test with molecule
        run: |
          cd ansible
          molecule test
        env:
          PY_COLORS: 1 
          ANSIBLE_FORCE_COLOR: 1
