---
name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - centos:7
          - centos:8
          - ubuntu:xenial
          - ubuntu:bionic
          - ubuntu:focal
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "ansible/roles/php"
      - name: molecule
        uses: robertdebock/molecule-action@2.6.1
        with:
          image: "${{ matrix.image }}"
