---
name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        image:
            #- centos:7
            - centos:latest
            #- ubuntu:xenial
            #- ubuntu:bionic
            #- ubuntu:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: set env
        run: |
          export NEW_REPOSITORY="/github/workspace/ansible/roles/php/"
          echo "::set-env name=PROJECT_PATH::$NEW_REPOSITORY"
          echo "::set-env name=MOLECULE_NO_LOG::false"
      - name: molecule
        uses: opsxin/molecule-action@2.6.3
        with:
          image: "${{ matrix.image }}"
