---
name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - centos:7
          - centos:8
          - ubuntu:xenial
          - ubuntu:bionic
          - ubuntu:focal
    steps:
      - name: checkout
        uses: actions/checkout@v2
        #with:
          #path: "${{ github.repository }}"
      - name: set env
        run: |
          export NEW_REPOSITORY="ansible/roles/php"
          echo "::set-env name=GITHUB_REPOSITORY::$NEW_REPOSITORY"
          echo "::set-env name=TEST::$NEW_REPOSITORY"
      - name: show env
        run: env
      - name: molecule
        uses: robertdebock/molecule-action@2.6.1
        with:
          image: "${{ matrix.image }}"
